---
apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${PROJECT_ID}-api.lab.kasna.cloud
spec:    
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: api
