---
steps:
- id: build api container
  name: 'gcr.io/cloud-builders/docker'
  dir: api
  args: ['build',
         '-t', 'gcr.io/${PROJECT_ID}/app:latest',
         '.']
- id: Push app image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         'gcr.io/${PROJECT_ID}/app:latest']

- id: Set env variables
  name: 'gcr.io/${PROJECT_ID}/envsubst'
  args:
  - 'files/*.yaml'
  env:
  - 'PROJECT_ID=${PROJECT_ID}'

- id: create db migration job
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'files/job.yaml'
  - '-n'
  - 'app'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=australia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${PROJECT_ID}-gke'
  - 'GCLOUD_PROJECT=${PROJECT_ID}'
