---
steps:
- id: build api container
  name: 'gcr.io/cloud-builders/docker'
  dir: api
  args: ['build',
         '-t', 'gcr.io/${PROJECT_ID}/api:latest',
         '.']         
- id: Push api image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         'gcr.io/${PROJECT_ID}/api:latest']

- id: Set api variables
  name: 'gcr.io/${PROJECT_ID}/envsubst'
  args:
  - 'frontend/src/common/api.service.js'
  env:
  - 'PROJECT_ID=${PROJECT_ID}'         

- id: build frontend container
  name: 'gcr.io/cloud-builders/docker'
  dir: frontend
  args: ['build',
         '-t', 'gcr.io/${PROJECT_ID}/frontend:latest',
         '.']

- id: Push frontend image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push',
         'gcr.io/${PROJECT_ID}/frontend:latest']        

- id: Set env variables
  name: 'gcr.io/${PROJECT_ID}/envsubst'
  dir: files
  args:
  - '*.yaml'
  env:
  - 'PROJECT_ID=${PROJECT_ID}'

- id: create api deployment
  name: 'gcr.io/cloud-builders/kubectl'
  dir: files  
  args:
  - 'apply'
  - '-f'
  - 'api-deployment.yaml'
  - '-n'
  - 'app'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=australia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${PROJECT_ID}-gke'
  - 'GCLOUD_PROJECT=${PROJECT_ID}'

- id: create api service
  name: 'gcr.io/cloud-builders/kubectl'
  dir: files  
  args:
  - 'apply'
  - '-f'
  - 'api-service.yaml'
  - '-n'
  - 'app'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=australia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${PROJECT_ID}-gke'
  - 'GCLOUD_PROJECT=${PROJECT_ID}'

- id: create frontend deployment
  name: 'gcr.io/cloud-builders/kubectl'
  dir: files  
  args:
  - 'apply'
  - '-f'
  - 'frontend-deployment.yaml'
  - '-n'
  - 'app'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=australia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${PROJECT_ID}-gke'
  - 'GCLOUD_PROJECT=${PROJECT_ID}'

- id: create frontend service
  name: 'gcr.io/cloud-builders/kubectl'
  dir: files  
  args:
  - 'apply'
  - '-f'
  - 'frontend-service.yaml'
  - '-n'
  - 'app'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=australia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${PROJECT_ID}-gke'
  - 'GCLOUD_PROJECT=${PROJECT_ID}'
