steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Check for existing scala-sbt image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/${PROJECT_ID}/scala-sbt:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=gcr.io/cloud-builders/javac:8'
  - '--build-arg=SBT_VERSION=1.2.8'
  - '--build-arg=SHA=f4b9fde91482705a772384c9ba6cdbb84d1c4f7a278fd2bfb34961cd9ed8e1d7'
  - '--tag=gcr.io/$PROJECT_ID/scala-sbt:latest'
  - 'project/.'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push scala-sbt image'
  args:
  - 'push'
  - 'gcr.io/${PROJECT_ID}/scala-sbt'
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  id: create-package
  args: ['assembly']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/kafka2avro', '.' ]
images:
- 'gcr.io/$PROJECT_ID/kafka2avro'  
