steps:
- id: Set env variables
  name: 'gcr.io/${PROJECT_ID}/envsubst'
  args: ['src/templates/*.yaml']
  env:
  - 'PROJECT_ID=${PROJECT_ID}'
  - 'LOCATION=australia-southeast1' 
- name: gcr.io/cloud-builders/gsutil
  id: upload-dags-to-bucket
  args: ['cp', '-r', 'src/*', 'gs://${PROJECT_ID}-storage/dags/']